handler: aime
dataset_path: AI-MO/aimo-validation-aime
dataset_split: train
question_key: problem
answer_key: answer
templating_parameters:
  # template: "Return your final response within \\boxed{{}}. {prompt}"
  template: "Solve the following math problem efficiently and clearly.  The last line of your response should be of the following format: 'Therefore, the final answer is: $\\boxed{{ANSWER}}$. I hope it is correct' (without quotes) where ANSWER is just the final number or expression that solves the problem. Think step by step before answering.\n\nProblem: {prompt}"
preprocess_config:
  url: "2024"
